---
- hosts: servers
  vars_files:
    - vars.yml
  sudo: true
  sudo_user: "{{ user }}"

  tasks:
  - name: Pull sources from the repository.
    git: repo={{ project_repo }} dest=/home/{{ user }}/projects/{{ project_name }}/ version={{ branch }}

  - name: Upgrade the virtualenv.
    pip: requirements=/home/{{ user }}/projects/{{ project_name }}/requirements.txt virtualenv=/home/{{ user }}/virtualenvs/{{ project_name }}

  - name: Sync Django Database.
    shell: /home/{{ user }}/projects/{{ project_name }}/manage.py syncdb --migrate --noinput