---
- hosts: itreta
  vars_files:
    - vars.yml
  sudo: true

  tasks:
  - name: Pull sources from the repository.
    git: repo={{ project_repo }} dest=/home/{{ user }}/projects/{{ project_name }}/code/ version=master

  - name: Upgrade the virtualenv.
    pip: requirements=/home/{{ user }}/projects/{{ project_name }}/code/requirements.txt virtualenv=/home/{{ user }}/virtualenvs/{{ project_name }}


  - name: Sync Django Database.
    shell: sudo /home/{{ user }}/virtualenvs/{{ project_name }}/bin/python /home/{{ user }}/projects/{{ project_name }}/code/manage.py migrate
    notify:
      - restart nginx
      - restart supervisor

  handlers:
    - include: handlers.yml